

export default {
    title_block_03: require('../assets/img/title_block_03.png'),
    product_block_03: require('../assets/img/product_block_03.jpg'),
    title_block_05: require('../assets/img/title_block_05.png'),
    product_block_05: require('../assets/img/product_block_05.jpg'),
    title_block_07: require('../assets/img/title_block_07.png'),
    product_block_07: require('../assets/img/product_block_07.jpg'),
    women_classic_1: require('../assets/img/women-classic-1.jpg'),
    women_classic_2: require('../assets/img/women-classic-2.jpg'),
    women_classic_3: require('../assets/img/women-classic-3.jpg'),
    women_classic_4: require('../assets/img/women-classic-4.jpg'),
    sale_off_1: require('../assets/img/sale-off-1.jpg'),
    sale_off_2: require('../assets/img/sale-off-2.jpg'),
    sale_off_3: require('../assets/img/sale-off-3.jpg'),
    sale_off_4: require('../assets/img/sale-off-4.jpg'),
    sale_off_5: require('../assets/img/sale-off-5.jpg'),
    img_googleplay: require('../assets/img/img-googleplay.jpg'),
    img_appstore: require('../assets/img/img-appstore.jpg'),
    img_payment: require('../assets/img/img-payment.png'),
    men_psy_1: require('../assets/img/men-psy-1-150x150.jpg'),
    men_psy_2: require('../assets/img/women-psy-2-150x150.jpg'),
    women_sunbaked_1: require('../assets/img/women-sunbaked-1-150x150.jpg'),
    women_sunbaked_2: require('../assets/img/women-sunbaked-2-150x150.jpg'),
    women_sunbaked_3: require('../assets/img/women-sunbaked-3-150x150.jpg'),
    news_1: require('../assets/img/news-1-150x150.jpg'),
    news_2: require('../assets/img/news-2-150x150.jpg'),
    news_3: require('../assets/img/news-3-150x150.jpg'),
    news_4: require('../assets/img/news-4-150x150.jpg'),
    news_5: require('../assets/img/news-5-150x150.png'),
    news_1_300: require('../assets/img/news-1-300x225.jpg'),
    news_2_300: require('../assets/img/news-2-300x229.jpg'),
    news_3_300: require('../assets/img/news-3-300x143.jpg'),
    news_4_300: require('../assets/img/news-4-300x200.jpg'),
    news_5_300: require('../assets/img/news-5-300x203.png'),
    news_6_300: require('../assets/img/news-6-300x225.jpg'),
    gioithieu: require('../assets/img/gioithieu.jpg'),
    banner_1: require('../assets/img/banner-1.jpg'),
    women_classic_1_1: require('../assets/img/women-classic-1-1-768x492.jpg'),
    logo_ghn: require('../assets/img/logo-ghn.jpg'),
    logo_ghtk: require('../assets/img/logo-ghtk.jpg'),
    logo_ninja_van: require('../assets/img/logo-ninja-van.jpg'),
    logo_shipchung: require('../assets/img/logo-shipchung.jpg'),
    logo_viettle_post: require('../assets/img/logo-viettle-post.jpg'),
    logo_vn_post: require('../assets/img/logo-vn-post.jpg'),
    logo_acb: require('../assets/img/logo-acb.jpg'),
    logo_techcombank: require('../assets/img/logo-techcombank.jpg'),
    logo_vib: require('../assets/img/logo-vib.jpg'),
    logo_vcb: require('../assets/img/logo-vcb.jpg'),
    logo_paypal: require('../assets/img/logo-paypal.jpg'),
    logo_mastercard: require('../assets/img/logo-mastercard.jpg'),
    women_classic_1_1: require('../assets/img/women-classic-1-1-768x492.jpg'),
    women_classic_1_2: require('../assets/img/women-classic-1-2-768x492.jpg'),
    women_classic_1_3: require('../assets/img/women-classic-1-3-768x492.jpg'),
    women_classic_1_4: require('../assets/img/women-classic-1-4-768x492.jpg')


}